package dha.lockrepo.view.swing;

import com.intellij.uiDesigner.core.Spacer;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import dha.lockrepo.business.TopSecretService;
import dha.lockrepo.business.TopSecretServiceImpl;
import dha.lockrepo.core.domains.TopSecretPieceBE;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class InfoWindow {
    private JPanel mainPanel;
    private JTextField usernameTxtField;
    private JTextField passwordTxtField;
    private JTextField descriptionTxtField;
    private JPanel formPanel;
    private JButton saveBtn;
    private JLabel titleLbl;
    private JTextField titleTxtField;

    private WindowManager manager;
    private TopSecretService secretService;
    /**
     * Item by title
     */
    private TopSecretPieceBE item;

    public InfoWindow(WindowManager windowManager) {
        this.manager = windowManager;
        secretService = TopSecretServiceImpl.getInstance();
        usernameTxtField.setColumns(20);
        passwordTxtField.setColumns(20);
        descriptionTxtField.setColumns(20);
        saveBtn.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                item.setTitle(titleTxtField.getText());
                item.setUsername(usernameTxtField.getText());
                item.setPasswd(passwordTxtField.getText());
                item.setInfo(descriptionTxtField.getText());
                secretService.update(item);
                titleTxtField.setVisible(false);
                titleLbl.setText(titleTxtField.getText());
                titleLbl.setVisible(true);
                InfoWindow.this.manager.packInfoWindow();
                InfoWindow.this.manager.update();
                InfoWindow.this.manager.closeAddWindow();
            }
        });
        titleLbl.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    titleLbl.setVisible(false);
                    titleTxtField.setVisible(true);
                    windowManager.packInfoWindow();
                }
            }
        });
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }


    public static void main(String[] args) {
        JFrame frame = new JFrame("InfoWindow");
        frame.setContentPane(new InfoWindow(null).mainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    public void setItem(TopSecretPieceBE item) {
        this.item = item;
        if (this.item == null) {
            throw new IllegalArgumentException("Item cannot be null");
        }
        System.out.println("Setting item " + item.getTitle());
        titleLbl.setText(this.item.getTitle());
        titleTxtField.setText(this.item.getTitle());
        usernameTxtField.setText(this.item.getUsername());
        passwordTxtField.setText(this.item.getPasswd());
        descriptionTxtField.setText(this.item.getInfo().orElse("no description specified"));
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new FormLayout("fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        mainPanel.setMinimumSize(new Dimension(100, 10));
        mainPanel.setBorder(BorderFactory.createTitledBorder(""));
        titleLbl = new JLabel();
        titleLbl.setFont(new Font(titleLbl.getFont().getName(), Font.BOLD, titleLbl.getFont().getSize()));
        titleLbl.setText("`");
        CellConstraints cc = new CellConstraints();
        mainPanel.add(titleLbl, cc.xy(3, 1));
        formPanel = new JPanel();
        formPanel.setLayout(new FormLayout("fill:d:noGrow,left:4dlu:noGrow,fill:d:grow", "center:d:grow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:d:grow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        formPanel.setMinimumSize(new Dimension(100, 10));
        mainPanel.add(formPanel, cc.xy(3, 3));
        final JLabel label1 = new JLabel();
        label1.setText("Username*");
        formPanel.add(label1, cc.xy(1, 5));
        usernameTxtField = new JTextField();
        usernameTxtField.setFont(new Font("NanumGothic", Font.BOLD, 14));
        formPanel.add(usernameTxtField, cc.xy(3, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label2 = new JLabel();
        label2.setText("Password*");
        formPanel.add(label2, cc.xy(1, 7));
        passwordTxtField = new JTextField();
        passwordTxtField.setFont(new Font("NanumGothic", Font.BOLD, 14));
        formPanel.add(passwordTxtField, cc.xy(3, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label3 = new JLabel();
        label3.setText("Description");
        formPanel.add(label3, cc.xy(1, 9));
        descriptionTxtField = new JTextField();
        descriptionTxtField.setFont(new Font("NanumGothic", Font.BOLD, 14));
        formPanel.add(descriptionTxtField, cc.xy(3, 9, CellConstraints.FILL, CellConstraints.DEFAULT));
        titleTxtField = new JTextField();
        titleTxtField.setVisible(false);
        formPanel.add(titleTxtField, cc.xy(1, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        final Spacer spacer1 = new Spacer();
        mainPanel.add(spacer1, cc.xy(3, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        final Spacer spacer2 = new Spacer();
        mainPanel.add(spacer2, cc.xy(5, 3, CellConstraints.DEFAULT, CellConstraints.FILL));
        final Spacer spacer3 = new Spacer();
        mainPanel.add(spacer3, cc.xy(1, 3, CellConstraints.DEFAULT, CellConstraints.FILL));
        saveBtn = new JButton();
        saveBtn.setText("Save");
        mainPanel.add(saveBtn, cc.xy(3, 7));
        final Spacer spacer4 = new Spacer();
        mainPanel.add(spacer4, cc.xy(3, 9, CellConstraints.FILL, CellConstraints.DEFAULT));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
