package dha.lockrepo.view.swing;

import com.intellij.uiDesigner.core.Spacer;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class PopupWindow {
    JPanel mainPanel;
    private JButton cancelButton;
    private JButton confirmButton;
    private JLabel messageLbl;

    private WindowManager windowManager;

    public PopupWindow(WindowManager windowManager, String message, Runnable onCancel, Runnable onConfirm) {
        this.mainPanel.setPreferredSize(new Dimension(200, 75));
        this.messageLbl.setText(message);
        this.windowManager = windowManager;
        cancelButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                System.out.println("Canceling");
                onCancel.run();
            }
        });
        confirmButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                System.out.println("Confirmed");
                onConfirm.run();
            }
        });
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("ConfirmDeleteWindow");
        frame.setContentPane(new PopupWindow(null, "asdas", System.out::println, null).mainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new FormLayout("fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:d:grow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        mainPanel.setMinimumSize(new Dimension(300, 84));
        final Spacer spacer1 = new Spacer();
        CellConstraints cc = new CellConstraints();
        mainPanel.add(spacer1, cc.xyw(3, 1, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        messageLbl = new JLabel();
        messageLbl.setText("");
        mainPanel.add(messageLbl, cc.xyw(3, 3, 3, CellConstraints.CENTER, CellConstraints.DEFAULT));
        cancelButton = new JButton();
        cancelButton.setForeground(new Color(-14709433));
        cancelButton.setText("Cancel");
        mainPanel.add(cancelButton, cc.xy(3, 5, CellConstraints.RIGHT, CellConstraints.DEFAULT));
        final Spacer spacer2 = new Spacer();
        mainPanel.add(spacer2, cc.xy(1, 5, CellConstraints.DEFAULT, CellConstraints.FILL));
        confirmButton = new JButton();
        confirmButton.setForeground(new Color(-4504287));
        confirmButton.setText("OK");
        mainPanel.add(confirmButton, cc.xy(5, 5));
        final Spacer spacer3 = new Spacer();
        mainPanel.add(spacer3, cc.xy(4, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
        final Spacer spacer4 = new Spacer();
        mainPanel.add(spacer4, cc.xy(7, 5, CellConstraints.DEFAULT, CellConstraints.FILL));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
